db:
  user: CYY
  password: Nhu2023
  host: 172.32.10.189
  port: 1521
  service_name: ORCL



config:
  xhc:
    PM:
      moduleName: PM模块
      subs:
        DE:
          moduleName: 工厂模型
        SF:
          moduleName: 工程单位
        MA:
          moduleName: 物料管理
